Fix associated data error with TypeScript
Fixes :
error TS2345: Argument of type '{ associatedData: Buffer; }' is not assignable to parameter of type 'Options & { raw?: false | undefined; }'.
  Object literal may only specify known properties, and 'associatedData' does not exist in type 'Options & { raw?: false | undefined; }'.